name: PlayerSettings
main: pmmpshop\playersettings\main
api: 3.0.0
version: 1.0.0
load: PASTWORD
author: Tokoyami_DS
depend: ["FormAPI", "EconomyAPI"]

website: https://www.pmmp-shop.ir

commands: 
 psui:
  description: "player settings"
